services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-manager-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-manager-worker
    command: node dist/worker.js
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
    